version: "3.9"

services:

  web:
    build: ./app
    ports:
      - 80:5000
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
    restart: on-failure
  
  db:
    image: redis:alpine
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
       - ./db:/docker-entrypoint-initdb.d/:ro
   