version: "3.9"

services:
  
  db:
    image: percona
    container_name: percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
       - ./db:/docker-entrypoint-initdb.d/:ro
  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  
  web:
    build: ./app
    container_name: flask
    ports:
      - 80:5000
    volumes:
      - ./app:/app
    restart: on-failure

volumes:
  app:
  db: