apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-flask
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: python:3.11-alpine
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: flask
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001