apiVersion: v1
kind: PersistentVolume
metadata:
  name: mi-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/volume/nginx"