apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: percona-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: percona-pv
  storageClassName: standard